# slimシンタックスハイライト
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

# typescript
[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = ['typescript']

# js
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'js']

# Go Plugins
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

# markdown 
[[plugins]]
repo = 'gabrielelana/vim-markdown'
on_ft = ['md', 'markdown']

# toml Syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# crystal
[[plugins]]
repo = 'rhysd/vim-crystal'
on_ft =['cr', 'crystal']

# deoplete-go
[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = ['go']
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

# インサートモードに入ったら読み込む
#[[plugins]]
#repo = 'Shougo/neocomplete.vim'
#on_i = 1

[[plugins]]
repo   = 'Shougo/unite.vim'

# unite.vim を読み込んだら一緒に読み込む
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

# 特定のコマンドを打ったら読み込む
[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']


[[plugins]]
repo  = 'Shougo/neosnippet'

[[plugins]]
repo  = 'Shougo/neosnippet-snippets'
on_source = ['Shougo/neosnippet']

# 特定のマッピングを使ったら読み込む
# 又、gvim でしか利用しない
[[plugins]]
repo   = 'thinca/vim-fontzoom'
on_cmd = ['Fontzoom']
on_map = ['<Plug>(fontzoom-']
gui    = 1
